version: '3.4'

services:
  mssql-container:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-container
    networks:
    - tmpNetwork
    environment:
      SA_PASSWORD: Zaq1@wsx 
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"   # Mapowanie portu kontenera na port hosta

  simulationengine.api:
    image: ${DOCKER_REGISTRY-}simulationengineapi
    build:
      context: .
      dockerfile: Services/SimulationEngine/SimulationEngine.API/Dockerfile

  tournament.api:
    image: ${DOCKER_REGISTRY-}tournamentapi
    build:
      context: .
      dockerfile: Services/Tournament.API/Tournament.API/Dockerfile


  webscrapingintegration.api:
    image: ${DOCKER_REGISTRY-}webscrapingintegrationapi
    build:
      context: .
      dockerfile: Services/WebScrapingIntegration/WebScrapingIntegration.API/Dockerfile
    networks:
    - tmpNetwork


  settings.api:
    image: ${DOCKER_REGISTRY-}settingsapi
    build:
      context: .
      dockerfile: Services/Settings/Settings.API/Dockerfile


  result.api:
    image: ${DOCKER_REGISTRY-}resultapi
    build:
      context: .
      dockerfile: Services/Result/Result.API/Dockerfile


  processmanager.api:
    image: ${DOCKER_REGISTRY-}processmanagerapi
    build:
      context: .
      dockerfile: Services/ProcessManager/ProcessManager.API/Dockerfile


  matchmanagment.api:
    image: ${DOCKER_REGISTRY-}matchmanagmentapi
    build:
      context: .
      dockerfile: Services/MatchManagment/MatchManagment.API/Dockerfile


  logger.api:
    container_name: Logger.API
    image: ${DOCKER_REGISTRY-}loggerapi
    build:
      context: .
      dockerfile: Services/Logger/Logger.API/Dockerfile
    environment:
    - DB_HOST=mssql-container
    - DB_NAME_LOGGER=Logger
    - DB_SA_PASSWORD=Zaq1@wsx
    networks:
    - tmpNetwork
  
    
    
    
    
  datahub.api:
    image: ${DOCKER_REGISTRY-}datahubapi
    build:
      context: .
      dockerfile: Services/DataHub/DataHub.API/Dockerfile
    environment:
    - DB_HOST=mssql-container
    - DB_NAME_DATAHUB=DataHub
    - DB_SA_PASSWORD=Zaq1@wsx
    networks:
    - tmpNetwork


  cache.api:
    image: ${DOCKER_REGISTRY-}cacheapi
    build:
      context: .
      dockerfile: Services/Cache/Cache.API/Dockerfile

  
volumes:
    sql-data:
networks:
  tmpNetwork:
