version: '3.4'

services:
  mssql-container:
    volumes:
      - sql-data:/var/opt/mssql
  
#  simulationengine.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "8004:80"

#  tournament.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "8005:80"


  webscrapingintegration.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "8003:80"


#  settings.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "8006:80"
#

#  result.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "8007:80"
#

  processmanager.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8099:80"


#  matchmanagment.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "8008:80"
#

  logger.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"


  datahub.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "8002:80"


  datahubapigw:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "7001:80"


  webscrapingintegrationgw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002:80"

